spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abduganiyev.ismoil001@gmail.com
    password: ntgmnccbrvuhviov
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    url: jdbc:postgresql://localhost:5432/simLine
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ismoil_0709
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret:
      expiry: 31560000000
      key: VGhpcyBpcyBrZXkgZm9yIEpXVApNeSBuYW1lIGlzIElzbW9pbApNeSBiaXJ0aCBkYXkgMDcuMDkuMjAwNw==
frontend:
  url: http://localhost:8080/auth/verify?token=