spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simline
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret:
      expiry: 31560000000
      key: VGhpcyBpcyBrZXkgZm9yIEpXVApNeSBuYW1lIGlzIElzbW9pbApNeSBiaXJ0aCBkYXkgMDcuMDkuMjAwNw==